### ISSUE TITLE
Backend server won't start

### ISSUE THREAD

**Issue by gondfreecs** [AlvaroIsrael/gobarber-app#134] opened 2021-06-26 05:24 UTC
when i start server i this got error:

[ERROR] 07:23:32 Error: Cannot register a type name as a singleton without a "to" token

![image](https://user-images.githubusercontent.com/35019742/123502823-73e3c700-d64f-11eb-834c-e305954d9967.png)

**Comment by AlvaroIsrael** [comment] 2021-06-26 14:07
Hello @gondfreecs, thanks for reporting this, ill look into it. Not entirely sure, but i believe you also need a database running to be able to run locally. If it is confirmed then I will update de documentation!

**Comment by AlvaroIsrael** [comment] 2021-06-26 14:20
Yeah that is it @gondfreecs! My documentation on how to run needs to be updated, you see, there is a file in the src folder called .env.example which holds the environment variables this app needs to run. This file needs to be renamed to .env, and the variables set properly.
The provider is throwing that exception because you probably didn't renamed the file and so the env.STORAGE_DRIVER is null when it should be set to 'disk' locally, but you also would need a local database running, the same process needs to be done with the file ormconfig.json.example.
I'll update the documentation explaining the whole process better so you can run it.

![image](https://user-images.githubusercontent.com/8402007/123515904-cd5bee00-d66f-11eb-996e-9d20d9440434.png)

**Comment by gondfreecs** [comment] 2021-06-26 14:38
Ho man, thank you for ur reactivity 
i create an db redis but i don't really know which parameter i need and where i can find it

i use this command:
docker run --name redisimageName -p 6379:6379 -d -t redis:alpine

![image](https://user-images.githubusercontent.com/35019742/123516524-c5667300-d69c-11eb-91e9-98ffd4b24a4d.png)

![image](https://user-images.githubusercontent.com/35019742/123517688-b84c8280-d6a2-11eb-9000-e54593db1552.png)

![image](https://user-images.githubusercontent.com/35019742/123517698-c39fae00-d6a2-11eb-9c37-24282518e6a7.png)

**Comment by AlvaroIsrael** [comment] 2021-06-26 16:07
Well fixing documentation will take sometime (because it's really outdated), but to help you, considerer this:
This app uses 3 databases: mongo, postgres, and redis (for cache management).

The ormconfig file will only hold the info for postgres and mongo:
You will need to provide the 'username', 'password' and 'database' name of your local databases  for it to work, both for postgres and mongo. You can install them using docker, but i don't have the full command line for this at hand so ill write that down in documentation later but you can google that and fill the following fields, the 'name' is also a parameter when you install the using docker i guess.

```typescript
[
  {
    "name": "",
    "type": "postgres",
    "host": "localhost",
    "post": 9999,
    "username": "",
    "password": "",
    "database": "",
    "entities": [
      "./src/modules/**/infra/typeorm/entities/*.ts"
    ],
    "migrations": [
      "./src/shared/infra/typeorm/migrations/*.ts"
    ],
    "cli": {
      "migrationsDir": "./src/shared/infra/typeorm/migrations"
    }
  },
  {
    "name": "",
    "type": "mongodb",
    "host": "localhost",
    "port": 9999,
    "database": "",
    "useUnifiedTopology": true,
    "entities": [
      "./src/modules/**/infra/typeorm/schemas/*.ts"
    ]
  }
]
```

For redis, you will have to provide the 3 environment variables in .env file:
REDIS_HOST=localhost
REDIS_PORT=YOUR LOCAL PORT NUMBER REDIS IS RUNNING
REDIS_PASSWORD=THE PASSWORD YOU SET UP WHEN INSTALLING REDIS

I am not 100% sure but the command should be: 
```bash
docker run -d --name "YOUR REDIS SERVER NAME" -e REDIS_PASSWORD="A PASSWORD FOR YOUR REDIS SERVER" -p "SERVER PORT":"LOCAL PORT ON YOUR MACHINE" bitnami/redis:latest
```

You could try that without quotes, to get redis up and running.
I'll explain the process better once the documentation is updated, but maybe this can get your started.

**Comment by gondfreecs** [comment] 2021-06-26 23:24
Thank you a lot, actually i have a probleme to setup all my var env can i have a good sample of ormconfig.json and .env

![image](https://user-images.githubusercontent.com/35019742/123528244-5a418e80-d6e6-11eb-8a97-3c34b3b0aa0c.png)

and that what i get with this param when i try to sign in an user

![image](https://user-images.githubusercontent.com/35019742/123530899-e3b18a80-d6ff-11eb-9d9d-d941629bd077.png)

**Comment by AlvaroIsrael** [comment] 2021-06-28 17:44
Hey @gondfreecs, check out the readme inside backend's folder:

- https://github.com/AlvaroIsrael/gobarber-app/blob/master/gobarber-backend/README.md
I updated the documentation (#136), hope it helps, if it does please leave a comment here so I can close this issue.

If it does not you can keep replying here. I will work on it until it works!

PS.: You will need to install docker on your local machine, so don't forget that because the tutorial does not cover a guide on how to install docker.

**Comment by AlvaroIsrael** [comment] 2021-07-09 16:03
Well @gondfreecs I will be closing this issue for now because i didn't get a reply after 13 days. In the future, if you decide to revisit this project, let me know! Thanks!

**Closed as completed by AlvaroIsrael** 2021-07-09 16:03 UTC
Labels: bug, documentation
